services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  kafka_a:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka_a
    container_name: kafka_a
    healthcheck:
      test: nc -z kafka_a 19092 || exit -1
      start_period: 5s
      interval: 5s
      timeout: 15s
      retries: 10
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_a:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafka_b:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka_b
    container_name: kafka_b
    healthcheck:
      test: nc -z kafka_b 19092 || exit -1
      start_period: 5s
      interval: 5s
      timeout: 15s
      retries: 10
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_b:19092,EXTERNAL://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    ports:
      - 9096:9096
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.6.2
    depends_on:
      kafka_a:
        condition: service_healthy
      kafka_b:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_a:19092,kafka_b:19092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - 8080:8080
